# build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/peak-suprstate-274220:$COMMIT_SHA', '.']
# push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/peak-suprstate-274220:$COMMIT_SHA']
# Deploy container image to Cloud Run
- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - 'run'
  - 'deploy'
  - 'peak-suprstate-274220'
  - '--image'
  - 'gcr.io/$PROJECT_ID/peak-suprstate-274220:$COMMIT_SHA'
  - '--region'
  - 'europe-west'
  - '--platform'
  - 'managed'
images:
- 'gcr.io/$PROJECT_ID/peak-suprstate-274220:$COMMIT_SHA'